### ISSUE TITLE
Migrate code from todo-listv-0

### ISSUE THREAD

**Issue by majirosstefan** [smetanka-jakub/todo-list-v2#1]
CMD only approach: git remote add/git push (not lost history)
or via GUI (Gitkraken, Sourcetree, etc) alebo bitbucket / not sure about github (not lost history)
via VS Code (new project, spravis initialize new repo, manual copy task) = (lost history)

**Comment by smetankajakub** [comment]
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/duplicating-a-repository
