### ISSUE TITLE
Implement Husky hooks for eslint (+ add rules)

### ISSUE THREAD

**Issue by majirosstefan** [smetanka-jakub/todo-list-v2#2]
Add following and fix any issues (or warnings)

- husky
- eslint
- prettier

**Comment by majirosstefan** [comment]
Consider ignoring some warning (**how to ignore eslint warnings / rules ** - per file, per line ) - demonstrate examples in one file 
- put into the knowledge repository

**Comment by majirosstefan** [comment]
Regarding husky, add pre-commit script to run eslint

**Comment by smetankajakub** [comment]
husky integrated, eslint prettier resolved comments
